server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /health {
        return 200 "ok";
        add_header Content-Type text/plain;
    }
    location /api/auth {
        proxy_pass http://auth-service:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/analysis {
        proxy_pass http://analysis-service:3002;
        proxy_set_header Host $host;
    }
    location /api/upload {
        proxy_pass http://analysis-service:3002;
        proxy_set_header Host $host;
        client_max_body_size 300M;
    }
    location /api/rnn {
        proxy_pass http://analysis-service:3002;
        proxy_set_header Host $host;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
